name: 前端自动部署流程

on:
  push:
    branches: [ main ] # 只有 main 分支提交才触发

# 【深度知识】给予流水线修改仓库内容的权限（必须写在 jobs 同级或上方）
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy: # 任务 ID
    runs-on: ubuntu-latest
    steps:
      - name: 第一步：拉取代码
        uses: actions/checkout@v4

      - name: 第二步：安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 第三步：安装依赖
        run: npm install

      - name: 第四步：打包项目
        run: npm run build

      - name: 第五步：部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # 这是一个现成的插件
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 自动生成，不需要你配置
          publish_dir: ./dist # 告诉插件把打包后的 dist 目录发出去