name: 前端 CI 流程
on:
  push:
    branches: [ main ] # 只有 main 分支变动才跑

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # 【深度优化】开启 npm 缓存，下次安装会极快

      - name: 安装依赖
        run: npm install

      - name: 检查格式 (Lint)
        run: npm run lint

      - name: 打包项目
        run: npm run build
      
      - name: 测试读取密钥
        run: echo "我的密钥是 ${{ secrets.MY_API_KEY }}"
        # 注意：GitHub 会在日志里自动把这个密钥显示为 ***，这就是安全性。